name: re
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.6
  - pip
  - pip:
    - beautifulsoup4==4.11.1
    - bs4==0.0.1
    - joblib==1.2.0
    - lxml==4.8.0
    - numpy==1.23.3
    - pandas==1.5.0
    - pillow==9.2.0
    - requests>=2.28
    - scikit-learn==1.1.2
    - scipy==1.9.1
    - selenium==4.2.0
    - streamlit==1.13.0
    - tqdm==4.64.1
    - urllib3==1.26.9
    - webdriver-manager==3.7.0
    - xgboost==1.6.2
    - zipp==3.8.1
    - plotly==5.10.0
    - matplotlib==3.6.0
    - jupyter==1.0.0
    - geopandas>=0.11
    - networkx>=2.8
    - pyproj>=3.3
    - Rtree>=1.0
    - Shapely>=1.8,<2.0
    - osmnx==1.2.2
    - py7zr==0.20.0
    - rioxarray==0.12.2
    - fasttext==0.9.2
    - compress-fasttext==0.1.3
    - gensim==4.2.0
    - streamlit-option-menu==0.3.2
    - streamlit-folium==0.6.15
    - folium==0.13.0
    - torch==1.12.0
    - torchvision==0.14.0
    - transformers==4.24.0


